FROM ubuntu:latest AS env_base
RUN apt-get update && apt-get install -y  git  curl build-essential cmake python3-dev python3.10 && apt-get clean \
&& curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py  && python3.10 get-pip.py
# Instantiate venv and pre-activate
RUN pip3 install --no-cache-dir --upgrade pip setuptools

FROM env_base AS base 
RUN git clone --recursive https://github.com/li-plus/chatglm.cpp.git && cd chatglm.cpp

RUN cd chatglm.cpp && python3 setup.py sdist bdist_wheel

CMD tail -f /dev/null
